// utils/buildTeamsData.js

import {
  NBA,
  NFL,
  MLB,
  MLS,
  NHL,
  WNBA,
  NCAA,
  WESTERN_CONFERENCE,
  EASTERN_CONFERENCE,
  NATIONAL_LEAGUE,
  AMERICAN_LEAGUE,
  NFC,
  AFC,
  ACC,
  BIG_10,
  BIG_12,
  PAC_12,
  SEC,
  ATLANTIC,
  CENTRAL,
  SOUTHEAST,
  NORTHWEST,
  PACIFIC,
  SOUTHWEST,
  EAST,
  WEST,
  NORTH,
  SOUTH,
  METROPOLITAN,
  AL,
  AK,
  AZ,
  AR,
  CA,
  CO,
  CT,
  DE,
  DC,
  FL,
  GA,
  HI,
  ID,
  IL,
  IN,
  IA,
  KS,
  KY,
  LA,
  ME,
  MD,
  MA,
  MI,
  MN,
  MS,
  MO,
  MT,
  NE,
  NV,
  NH,
  NJ,
  NM,
  NY,
  NC,
  ND,
  OH,
  OK,
  OR,
  PA,
  RI,
  SC,
  SD,
  TN,
  TX,
  UT,
  VT,
  VA,
  WA,
  WV,
  WI,
  WY,
  CAN,
} from "../constants/constants";

const teamsData = {
  teams: [
    // NBA
    {
      id: 1,
      name1: "Boston",
      name2: "Celtics",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: MA,
    },
    {
      id: 2,
      name1: "Brooklyn",
      name2: "Nets",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: NY,
    },
    {
      id: 3,
      name1: "New York",
      name2: "Knicks",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: NY,
    },
    {
      id: 4,
      name1: "Philadelphia",
      name2: "76ers",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: PA,
    },
    {
      id: 5,
      name1: "Toronto",
      name2: "Raptors",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: CAN,
    },
    {
      id: 6,
      name1: "Chicago",
      name2: "Bulls",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: CENTRAL,
      state: IL,
    },
    {
      id: 7,
      name1: "Cleveland",
      name2: "Cavaliers",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: CENTRAL,
      state: OH,
    },
    {
      id: 8,
      name1: "Detroit",
      name2: "Pistons",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: CENTRAL,
      state: MI,
    },
    {
      id: 9,
      name1: "Indiana",
      name2: "Pacers",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: CENTRAL,
      state: IN,
    },
    {
      id: 10,
      name1: "Milwaukee",
      name2: "Bucks",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: CENTRAL,
      state: WI,
    },
    {
      id: 11,
      name1: "Atlanta",
      name2: "Hawks",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: SOUTHEAST,
      state: GA,
    },
    {
      id: 12,
      name1: "Charlotte",
      name2: "Hornets",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: SOUTHEAST,
      state: NC,
    },
    {
      id: 13,
      name1: "Miami",
      name2: "Heat",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: SOUTHEAST,
      state: FL,
    },
    {
      id: 14,
      name1: "Orlando",
      name2: "Magic",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: SOUTHEAST,
      state: FL,
    },
    {
      id: 15,
      name1: "Washington",
      name2: "Wizards",
      league: NBA,
      conference: EASTERN_CONFERENCE,
      division: SOUTHEAST,
      state: DC,
    },
    {
      id: 16,
      name1: "Denver",
      name2: "Nuggets",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: NORTHWEST,
      state: CO,
    },
    {
      id: 17,
      name1: "Minnesota",
      name2: "Timberwolves",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: NORTHWEST,
      state: MN,
    },
    {
      id: 18,
      name1: "Oklahoma City",
      name2: "Thunder",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: NORTHWEST,
      state: OK,
    },
    {
      id: 19,
      name1: "Portland",
      name2: "Trail Blazers",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: NORTHWEST,
      state: OR,
    },
    {
      id: 20,
      name1: "Utah",
      name2: "Jazz",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: NORTHWEST,
      state: UT,
    },
    {
      id: 21,
      name1: "Golden State",
      name2: "Warriors",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: CA,
    },
    {
      id: 22,
      name1: "Los Angeles",
      name2: "Clippers",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: CA,
    },
    {
      id: 23,
      name1: "Los Angeles",
      name2: "Lakers",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: CA,
    },
    {
      id: 24,
      name1: "Phoenix",
      name2: "Suns",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: AZ,
    },
    {
      id: 25,
      name1: "Sacramento",
      name2: "Kings",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: CA,
    },
    {
      id: 26,
      name1: "Dallas",
      name2: "Mavericks",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: SOUTHWEST,
      state: TX,
    },
    {
      id: 27,
      name1: "Houston",
      name2: "Rockets",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: SOUTHWEST,
      state: TX,
    },
    {
      id: 28,
      name1: "Memphis",
      name2: "Grizzlies",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: SOUTHWEST,
      state: TN,
    },
    {
      id: 29,
      name1: "New Orleans",
      name2: "Pelicans",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: SOUTHWEST,
      state: LA,
    },
    {
      id: 30,
      name1: "San Antonio",
      name2: "Spurs",
      league: NBA,
      conference: WESTERN_CONFERENCE,
      division: SOUTHWEST,
      state: TX,
    },

    // NFL
    {
      id: 31,
      name1: "Buffalo",
      name2: "Bills",
      league: NFL,
      conference: AFC,
      division: EAST,
      state: NY,
    },
    {
      id: 32,
      name1: "Miami",
      name2: "Dolphins",
      league: NFL,
      conference: AFC,
      division: EAST,
      state: FL,
    },
    {
      id: 33,
      name1: "New England",
      name2: "Patriots",
      league: NFL,
      conference: AFC,
      division: EAST,
      state: MA,
    },
    {
      id: 34,
      name1: "New York",
      name2: "Jets",
      league: NFL,
      conference: AFC,
      division: EAST,
      state: NY,
    },
    {
      id: 35,
      name1: "Baltimore",
      name2: "Ravens",
      league: NFL,
      conference: AFC,
      division: NORTH,
      state: MD,
    },
    {
      id: 36,
      name1: "Cincinnati",
      name2: "Bengals",
      league: NFL,
      conference: AFC,
      division: NORTH,
      state: OH,
    },
    {
      id: 37,
      name1: "Cleveland",
      name2: "Browns",
      league: NFL,
      conference: AFC,
      division: NORTH,
      state: OH,
    },
    {
      id: 38,
      name1: "Pittsburgh",
      name2: "Steelers",
      league: NFL,
      conference: AFC,
      division: NORTH,
      state: PA,
    },
    {
      id: 39,
      name1: "Houston",
      name2: "Texans",
      league: NFL,
      conference: AFC,
      division: SOUTH,
      state: TX,
    },
    {
      id: 40,
      name1: "Indianapolis",
      name2: "Colts",
      league: NFL,
      conference: AFC,
      division: SOUTH,
      state: IN,
    },
    {
      id: 41,
      name1: "Jacksonville",
      name2: "Jaguars",
      league: NFL,
      conference: AFC,
      division: SOUTH,
      state: FL,
    },
    {
      id: 42,
      name1: "Tennessee",
      name2: "Titans",
      league: NFL,
      conference: AFC,
      division: SOUTH,
      state: TN,
    },
    {
      id: 43,
      name1: "Denver",
      name2: "Broncos",
      league: NFL,
      conference: AFC,
      division: WEST,
      state: CO,
    },
    {
      id: 44,
      name1: "Kansas City",
      name2: "Chiefs",
      league: NFL,
      conference: AFC,
      division: WEST,
      state: MO,
    },
    {
      id: 45,
      name1: "Las Vegas",
      name2: "Raiders",
      league: NFL,
      conference: AFC,
      division: WEST,
      state: NV,
    },
    {
      id: 46,
      name1: "Los Angeles",
      name2: "Chargers",
      league: NFL,
      conference: AFC,
      division: WEST,
      state: CA,
    },
    {
      id: 47,
      name1: "Dallas",
      name2: "Cowboys",
      league: NFL,
      conference: NFC,
      division: EAST,
      state: TX,
    },
    {
      id: 48,
      name1: "New York",
      name2: "Giants",
      league: NFL,
      conference: NFC,
      division: EAST,
      state: NY,
    },
    {
      id: 49,
      name1: "Philadelphia",
      name2: "Eagles",
      league: NFL,
      conference: NFC,
      division: EAST,
      state: PA,
    },
    {
      id: 50,
      name1: "Washington",
      name2: "Football Team",
      league: NFL,
      conference: NFC,
      division: EAST,
      state: DC,
    },
    {
      id: 51,
      name1: "Chicago",
      name2: "Bears",
      league: NFL,
      conference: NFC,
      division: NORTH,
      state: IL,
    },
    {
      id: 52,
      name1: "Detroit",
      name2: "Lions",
      league: NFL,
      conference: NFC,
      division: NORTH,
      state: MI,
    },
    {
      id: 53,
      name1: "Green Bay",
      name2: "Packers",
      league: NFL,
      conference: NFC,
      division: NORTH,
      state: WI,
    },
    {
      id: 54,
      name1: "Minnesota",
      name2: "Vikings",
      league: NFL,
      conference: NFC,
      division: NORTH,
      state: MN,
    },
    {
      id: 55,
      name1: "Atlanta",
      name2: "Falcons",
      league: NFL,
      conference: NFC,
      division: SOUTH,
      state: GA,
    },
    {
      id: 56,
      name1: "Carolina",
      name2: "Panthers",
      league: NFL,
      conference: NFC,
      division: SOUTH,
      state: NC,
    },
    {
      id: 57,
      name1: "New Orleans",
      name2: "Saints",
      league: NFL,
      conference: NFC,
      division: SOUTH,
      state: LA,
    },
    {
      id: 58,
      name1: "Tampa Bay",
      name2: "Buccaneers",
      league: NFL,
      conference: NFC,
      division: SOUTH,
      state: FL,
    },
    {
      id: 59,
      name1: "Arizona",
      name2: "Cardinals",
      league: NFL,
      conference: NFC,
      division: WEST,
      state: AZ,
    },
    {
      id: 60,
      name1: "Los Angeles",
      name2: "Rams",
      league: NFL,
      conference: NFC,
      division: WEST,
      state: CA,
    },
    {
      id: 61,
      name1: "San Francisco",
      name2: "49ers",
      league: NFL,
      conference: NFC,
      division: WEST,
      state: CA,
    },
    {
      id: 62,
      name1: "Seattle",
      name2: "Seahawks",
      league: NFL,
      conference: NFC,
      division: WEST,
      state: WA,
    },

    // MLB (92)
    {
      id: 63,
      name1: "Baltimore",
      name2: "Orioles",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: EAST,
      state: MD,
    },
    {
      id: 64,
      name1: "Boston",
      name2: "Red Sox",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: EAST,
      state: MA,
    },
    {
      id: 65,
      name1: "New York",
      name2: "Yankees",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: EAST,
      state: NY,
    },
    {
      id: 66,
      name1: "Tampa Bay",
      name2: "Rays",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: EAST,
      state: FL,
    },
    {
      id: 67,
      name1: "Toronto",
      name2: "Blue Jays",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: EAST,
      state: CAN,
    },
    {
      id: 68,
      name1: "Chicago",
      name2: "White Sox",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: CENTRAL,
      state: IL,
    },
    {
      id: 69,
      name1: "Cleveland",
      name2: "Guardians",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: CENTRAL,
      state: OH,
    },
    {
      id: 70,
      name1: "Detroit",
      name2: "Tigers",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: CENTRAL,
      state: MI,
    },
    {
      id: 71,
      name1: "Kansas City",
      name2: "Royals",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: CENTRAL,
      state: MO,
    },
    {
      id: 72,
      name1: "Minnesota",
      name2: "Twins",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: CENTRAL,
      state: MN,
    },
    {
      id: 73,
      name1: "Houston",
      name2: "Astros",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: WEST,
      state: TX,
    },
    {
      id: 74,
      name1: "Los Angeles",
      name2: "Angels",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: WEST,
      state: CA,
    },
    {
      id: 75,
      name1: "Oakland",
      name2: "Athletics",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: WEST,
      state: CA,
    },
    {
      id: 76,
      name1: "Seattle",
      name2: "Mariners",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: WEST,
      state: WA,
    },
    {
      id: 77,
      name1: "Texas",
      name2: "Rangers",
      league: MLB,
      conference: AMERICAN_LEAGUE,
      division: WEST,
      state: TX,
    },
    {
      id: 78,
      name1: "Atlanta",
      name2: "Braves",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: EAST,
      state: GA,
    },
    {
      id: 79,
      name1: "Miami",
      name2: "Marlins",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: EAST,
      state: FL,
    },
    {
      id: 80,
      name1: "New York",
      name2: "Mets",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: EAST,
      state: NY,
    },
    {
      id: 81,
      name1: "Philadelphia",
      name2: "Phillies",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: EAST,
      state: PA,
    },
    {
      id: 82,
      name1: "Washington",
      name2: "Nationals",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: EAST,
      state: DC,
    },
    {
      id: 83,
      name1: "Chicago",
      name2: "Cubs",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: CENTRAL,
      state: IL,
    },
    {
      id: 84,
      name1: "Cincinnati",
      name2: "Reds",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: CENTRAL,
      state: OH,
    },
    {
      id: 85,
      name1: "Milwaukee",
      name2: "Brewers",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: CENTRAL,
      state: WI,
    },
    {
      id: 86,
      name1: "Pittsburgh",
      name2: "Pirates",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: CENTRAL,
      state: PA,
    },
    {
      id: 87,
      name1: "St. Louis",
      name2: "Cardinals",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: CENTRAL,
      state: MO,
    },
    {
      id: 88,
      name1: "Arizona",
      name2: "Diamondbacks",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: WEST,
      state: AZ,
    },
    {
      id: 89,
      name1: "Colorado",
      name2: "Rockies",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: WEST,
      state: CO,
    },
    {
      id: 90,
      name1: "Los Angeles",
      name2: "Dodgers",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: WEST,
      state: CA,
    },
    {
      id: 91,
      name1: "San Diego",
      name2: "Padres",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: WEST,
      state: CA,
    },
    {
      id: 92,
      name1: "San Francisco",
      name2: "Giants",
      league: MLB,
      conference: NATIONAL_LEAGUE,
      division: WEST,
      state: CA,
    },

    // MLS (121)
    {
      id: 93,
      name1: "Atlanta",
      name2: "United FC",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: GA,
    },
    {
      id: 94,
      name1: "Charlotte",
      name2: "FC",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: NC,
    },
    {
      id: 95,
      name1: "Chicago",
      name2: "Fire FC",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: IL,
    },
    {
      id: 96,
      name1: "Columbus",
      name2: "Crew",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: OH,
    },
    {
      id: 97,
      name1: "FC",
      name2: "Cincinnati",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: OH,
    },
    {
      id: 98,
      name1: "D.C.",
      name2: "United",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: DC,
    },
    {
      id: 99,
      name1: "Inter Miami",
      name2: "CF",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: FL,
    },
    {
      id: 100,
      name1: "CF",
      name2: "Montreal",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: CAN,
    },
    {
      id: 101,
      name1: "Nashville",
      name2: "SC",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: TN,
    },
    {
      id: 102,
      name1: "New England",
      name2: "Revolution",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: MA,
    },
    {
      id: 103,
      name1: "New York City",
      name2: "FC",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: NY,
    },
    {
      id: 104,
      name1: "New York",
      name2: "Red Bulls",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: NY,
    },
    {
      id: 105,
      name1: "Orlando City",
      name2: "SC",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: FL,
    },
    {
      id: 106,
      name1: "Philadelphia",
      name2: "Union",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: PA,
    },
    {
      id: 107,
      name1: "Toronto",
      name2: "FC",
      league: MLS,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: CAN,
    },
    {
      id: 108,
      name1: "Austin",
      name2: "FC",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: TX,
    },
    {
      id: 109,
      name1: "Colorado",
      name2: "Rapids",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: CO,
    },
    {
      id: 110,
      name1: "FC",
      name2: "Dallas",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: TX,
    },
    {
      id: 111,
      name1: "Houston",
      name2: "Dynamo FC",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: TX,
    },
    {
      id: 112,
      name1: "LA",
      name2: "Galaxy",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: CA,
    },
    {
      id: 113,
      name1: "Los Angeles",
      name2: "FC",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: CA,
    },
    {
      id: 114,
      name1: "Minnesota",
      name2: "United FC",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: MN,
    },
    {
      id: 115,
      name1: "Portland",
      name2: "Timbers",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: OR,
    },
    {
      id: 116,
      name1: "Real",
      name2: "Salt Lake",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: UT,
    },
    {
      id: 117,
      name1: "San Jose",
      name2: "Earthquakes",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: CA,
    },
    {
      id: 118,
      name1: "Seattle",
      name2: "Sounders FC",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: WA,
    },
    {
      id: 119,
      name1: "Sporting",
      name2: "Kansas City",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: MO,
    },
    {
      id: 120,
      name1: "St. Louis",
      name2: "City SC",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: MO,
    },
    {
      id: 121,
      name1: "Vancouver",
      name2: "Whitecaps FC",
      league: MLS,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: CAN,
    },

    // NHL
    {
      id: 122,
      name1: "Carolina",
      name2: "Hurricanes",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: METROPOLITAN,
      state: NC,
    },
    {
      id: 123,
      name1: "Columbus",
      name2: "Blue Jackets",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: METROPOLITAN,
      state: OH,
    },
    {
      id: 124,
      name1: "New Jersey",
      name2: "Devils",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: METROPOLITAN,
      state: NJ,
    },
    {
      id: 125,
      name1: "New York",
      name2: "Islanders",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: METROPOLITAN,
      state: NY,
    },
    {
      id: 126,
      name1: "New York",
      name2: "Rangers",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: METROPOLITAN,
      state: NY,
    },
    {
      id: 127,
      name1: "Philadelphia",
      name2: "Flyers",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: METROPOLITAN,
      state: PA,
    },
    {
      id: 128,
      name1: "Pittsburgh",
      name2: "Penguins",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: METROPOLITAN,
      state: PA,
    },
    {
      id: 129,
      name1: "Washington",
      name2: "Capitals",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: METROPOLITAN,
      state: DC,
    },
    {
      id: 130,
      name1: "Boston",
      name2: "Bruins",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: MA,
    },
    {
      id: 131,
      name1: "Buffalo",
      name2: "Sabres",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: NY,
    },
    {
      id: 132,
      name1: "Detroit",
      name2: "Red Wings",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: MI,
    },
    {
      id: 133,
      name1: "Florida",
      name2: "Panthers",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: FL,
    },
    {
      id: 134,
      name1: "Montreal",
      name2: "Canadiens",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: CAN,
    },
    {
      id: 135,
      name1: "Ottawa",
      name2: "Senators",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: CAN,
    },
    {
      id: 136,
      name1: "Tampa Bay",
      name2: "Lightning",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: FL,
    },
    {
      id: 137,
      name1: "Toronto",
      name2: "Maple Leafs",
      league: NHL,
      conference: EASTERN_CONFERENCE,
      division: ATLANTIC,
      state: CAN,
    },
    {
      id: 138,
      name1: "Arizona",
      name2: "Coyotes",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: CENTRAL,
      state: AZ,
    },
    {
      id: 139,
      name1: "Chicago",
      name2: "Blackhawks",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: CENTRAL,
      state: IL,
    },
    {
      id: 140,
      name1: "Colorado",
      name2: "Avalanche",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: CENTRAL,
      state: CO,
    },
    {
      id: 141,
      name1: "Dallas",
      name2: "Stars",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: CENTRAL,
      state: TX,
    },
    {
      id: 142,
      name1: "Minnesota",
      name2: "Wild",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: CENTRAL,
      state: MN,
    },
    {
      id: 143,
      name1: "Nashville",
      name2: "Predators",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: CENTRAL,
      state: TN,
    },
    {
      id: 144,
      name1: "St. Louis",
      name2: "Blues",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: CENTRAL,
      state: MO,
    },
    {
      id: 145,
      name1: "Winnipeg",
      name2: "Jets",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: CENTRAL,
      state: CAN,
    },
    {
      id: 146,
      name1: "Anaheim",
      name2: "Ducks",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: CA,
    },
    {
      id: 147,
      name1: "Calgary",
      name2: "Flames",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: CAN,
    },
    {
      id: 148,
      name1: "Edmonton",
      name2: "Oilers",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: CAN,
    },
    {
      id: 149,
      name1: "Los Angeles",
      name2: "Kings",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: CA,
    },
    {
      id: 150,
      name1: "San Jose",
      name2: "Sharks",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: CA,
    },
    {
      id: 151,
      name1: "Seattle",
      name2: "Kraken",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: WA,
    },
    {
      id: 152,
      name1: "Vancouver",
      name2: "Canucks",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: CAN,
    },
    {
      id: 153,
      name1: "Vegas",
      name2: "Golden Knights",
      league: NHL,
      conference: WESTERN_CONFERENCE,
      division: PACIFIC,
      state: NV,
    },

    // WNBA
    {
      id: 154,
      name1: "Atlanta",
      name2: "Dream",
      league: WNBA,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: GA,
    },
    {
      id: 155,
      name1: "Chicago",
      name2: "Sky",
      league: WNBA,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: IL,
    },
    {
      id: 156,
      name1: "Connecticut",
      name2: "Sun",
      league: WNBA,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: CT,
    },
    {
      id: 157,
      name1: "Indiana",
      name2: "Fever",
      league: WNBA,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: IN,
    },
    {
      id: 158,
      name1: "New York",
      name2: "Liberty",
      league: WNBA,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: NY,
    },
    {
      id: 159,
      name1: "Washington",
      name2: "Mystics",
      league: WNBA,
      conference: EASTERN_CONFERENCE,
      division: null,
      state: DC,
    },
    {
      id: 160,
      name1: "Dallas",
      name2: "Wings",
      league: WNBA,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: TX,
    },
    {
      id: 161,
      name1: "Las Vegas",
      name2: "Aces",
      league: WNBA,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: NV,
    },
    {
      id: 162,
      name1: "Los Angeles",
      name2: "Sparks",
      league: WNBA,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: CA,
    },
    {
      id: 163,
      name1: "Minnesota",
      name2: "Lynx",
      league: WNBA,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: MN,
    },
    {
      id: 164,
      name1: "Phoenix",
      name2: "Mercury",
      league: WNBA,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: AZ,
    },
    {
      id: 165,
      name1: "Seattle",
      name2: "Storm",
      league: WNBA,
      conference: WESTERN_CONFERENCE,
      division: null,
      state: WA,
    },

    // NCAA
    //ACC

    //Big 12

    //Big Ten

    //Pac-12

    //SEC
  ],
};

export default teamsData;
